---
# tasks file for acro.drush

- name: Install drush from phar
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/8.1.17/drush.phar
    checksum: sha256:9c5b245c3a437851bded21fd52014dddd1f5eb8f3e9ee8230047533bd02829ba
    dest: /usr/local/bin/drush
    group: root
    owner: root
    mode: 0755
