---
# tasks file for acro.drush

- name: Install drush from phar
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/8.1.15/drush.phar
    checksum: sha256:6999d72e51577b1e20cfaec87152d9905b714f5812861692877b8424a4e2358a
    dest: /usr/local/bin/drush
    group: root
    owner: root
    mode: 0755
